### ISSUE TITLE
Add `README.md`

### ISSUE THREAD

**Issue by za** [NextronSystems/asgard-manual#6]
Hi there!

What if we add `README.md` showing hyperlink to https://asgard-manual.nextron-systems.com/en/2.12/index.html# telling that this is the source for the docs?

**Comment by redteampanda-ng** [comment]
Hey,

this sounds like a good idea. I will work something out and upload it.

**Comment by redteampanda-ng** [comment]
Hi,

I just created the readme file. If you are missing anything from there, feel free to open a pull request.

**Comment by za** [comment]
Nothing for now @redteampanda-ng Thanks for adding it!
